# Generated by Django 3.1.1 on 2020-09-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('TY', 'Toys'), ('DP', 'Diapers'), ('CL', 'Clothes'), ('BK', 'Books'), ('OT', 'Others')], default='OT', max_length=2)),
                ('age', models.CharField(choices=[('3M', '3m'), ('6M', '6m'), ('9M', '9m'), ('1y', '1yr'), ('2Y', '2yr'), ('3Y', '3yr'), ('4Y', '4yr'), ('5Y', '5yr')], default='3M', max_length=2)),
                ('condition', models.CharField(choices=[('NW', 'New'), ('LN', 'Like a new'), ('GD', 'Good'), ('FR', 'Fair')], max_length=2)),
                ('sold', models.BooleanField(default=True)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
