# Generated by Django 3.1.1 on 2020-09-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='age',
            field=models.CharField(choices=[('3M', '3m'), ('6M', '6m'), ('9M', '9m'), ('1y', '1yr'), ('2Y', '2yr'), ('3Y', '3yr'), ('4Y', '4yr'), ('5Y', '5yr')], max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('TY', 'Toys'), ('DP', 'Diapers'), ('CL', 'Clothes'), ('BK', 'Books'), ('OT', 'Others')], max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
