# Generated by Django 3.1.1 on 2020-09-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='searches',
            field=models.ManyToManyField(to='main_app.Search'),
        ),
    ]
