# Generated by Django 3.1.1 on 2020-10-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20201002_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='a@gmail.com', max_length=254),
        ),
    ]
